### PR TITLE
ES2016 Support

### PR DESCRIPTION
**Pull request by mikeal**
This is an additional commit on top of @bcoe's PR upgrading the deps for additional language support.

### CODE REVIEW

**Comment by mikeal** [comment]
Something is still broken but I'm not quite sure what it is.

With this branch I can get the browserify transform to succeed. I can also integrate the transform into a set that creates a bundle and those tests pass, with the transform include, but only if I don't enable coverage in tap.

Basically, `tap tests/test-*.js` works but `tap tests/test-*.js --coverage-report=lcov` fails with errors stating:

```
  not ok Evaluation failed: ReferenceError: cov_vnbsudnht is not defined     at <anonymous>:1:12
    stack: |
      Frame._rawEvaluate (node_modules/puppeteer/lib/FrameManager.js:264:13)
      <anonymous>
    at:
      line: 264
      column: 13
      file: node_modules/puppeteer/lib/FrameManager.js
      function: Frame._rawEvaluate
    test: basic
    source: >
      throw new Error('Evaluation failed: ' +
      helper.getExceptionMessage(exceptionDetails));
```

**Comment by mikeal** [comment]
Any thoughts @bcoe @devongovett @isaacs?

**Comment by mikeal** [comment]
I pushed the current status of integrating this into some real tests: https://github.com/mikeal/gza/tree/coverage

**Comment by alexindigo** [comment]
@mikeal Should it be merged on top of @bcoe's PR or it's self-suffcient? 

Looks like we're ditching `istanbul` completely in favor of `nyc` + `istanbul-lib-instrument`, or did I miss something?

**Comment by alexindigo** [comment]
Tested with existing projects – looks fine.
I'm ready to merge if you think it's ready.

**Comment by mikeal** [comment]
I can't get it to work yet in my `puppeteer + tap` setup but I'm much closer with this than I am the current version.

But if the tests are all passing it's probably ready.

**Comment by bcoe** [comment]
@mikeal I should be able to take a look tonight at your issue; have been heads down working on a yargs release.

**Comment by bcoe** [comment]
@mikeal @alexindigo I'm not quite sure why you're seeing this `cov_` undefined issue, my guess is something being done within the puppeteer library to clobber this value. Having said this, this isn't actually how I think you should approach collecting coverage for the integration tests.

You care about the `__coverage__` variable being set inside the `page` context of Chrome, not in the Node environment. Here's how you can go about capturing that:

```js
const path = require('path')
const rimraf = require('rimraf')
const fs = require('fs')
const mkdirp = require('mkdirp')
const COVERAGE_FOLDER = './.nyc_output'

rimraf.sync(COVERAGE_FOLDER)

function outputCoverage (page) {
  return new Promise(async (resolve, reject) => {
    mkdirp.sync(COVERAGE_FOLDER)
    page.once('console', payload => {
      const cov = JSON.parse(payload)
      fs.writeFileSync(
        path.resolve(COVERAGE_FOLDER, `${Date.now()}.json`),
        JSON.stringify(cov, null, 2),
        'utf8'
      )
      return resolve()
    })
    await page.evaluate(async () => {
      console.log(JSON.stringify(__coverage__))
    })
  })
}

test('basic', async t => {
  t.plan(1)
  let page = await getPage(t, `<test-one></test-one>`)
  await page.waitFor('test-one render')
  await page.evaluate(async () => {
    same(clean(document.querySelector('test-one render').textContent), 'Test')
  })
  await outputCoverage(page)
  await page.close()
})
```

☝️ I thought this was pretty darn cool, and probably would be worth a blog post somewhere.

Once you run the browser tests with the above helper, you can view reports by running:

`nyc report --reporter=html --reporter=text`

screen shot 2017-10-14 at 11 27 30 pm

Logistically, I would probably run your tests in two parts:

1. for Node.js tests, simply run `tap --coverage`.
2. for the integration tests, use the trick I shared above.

**Comment by alexindigo** [comment]
I'm using https://www.npmjs.com/package/obake for in browser coverage.
It does something similar: https://github.com/alexindigo/obake/blob/master/lib/phantom.js

**Comment by alexindigo** [comment]
Published `browserify-istanbul@3.0.0`. Thank you.

**Comment by mikeal** [comment]
@bcoe why the rimraf at the top? I'm worried that this will kill the coverage reporting for any non-browser tests run in the same tap session.

**Comment by mikeal** [comment]
@bcoe so, with your code I can get all the tests to run just fine, even with `tap` normally.

But the moment that I run with --coverage it blows up with that error from before. I wonder what tap's coverage enables that would break this?

Is it possible that it's actually altering what gets put into the bundle?

**Comment by bcoe** [comment]
@mikeal the `rimraf` was only there as a demonstration of how you'd probably want to cleanup that folder between full test runs.

There's definitely an issue I saw with `puppeteer` related to instrumenting files, my guess is that `puppeteer` is potentially messing with the global state as part of its bootstrapping process. This shouldn't be an issue though. I would have two test stanzas in your `package.json`:

1. `test:unit` which can run all the non-browser-integration tests with `--coverage` enabled.
2. `test:integration` which would run any test files that lean on `puppeteer`, this mode would not have `--coverage` enabled (as you'll be instrumenting the source for coverage separately using `browserify-istanbul` and the hook that writes `__coverage__` to disk).

It might be worth opening an issue with `puppeteer` to see why they are nuking the `cov_vnbsudnht` variable, but I think you should be able to workaround this by splitting your tests into these two parts -- tldr; because the code is being instrumented when it's injected into the browser, and coverage is collected in the browser process,`--coverage` is a noop at best, and at worst could potentially introduce some odd behavior.

_Edit: you'd probably also want to add a `report` stanza which calls, `nyc report` and runs after both `test:unit` and `test:integration`; If you make sure that `test:unit` runs first, and write `__coverage__` into the same `.nyc_output` folder, you should end up getting the combined coverage report._

**Comment by mikeal** [comment]
@bcoe my question is though, where does the cov_vnbsudnht variable even come from? if it's injected by browserify-istanbul then it's presumably running even when --coverage is not enabled.

It's hard for me to place this as a puppeteer bug when it appears to be passing or failing based on tap options :(

I can see how having two stanzas can be a workaround but, because the coverage can't be integrated between the two sweets, i'm not going to be able to automate coverage pass thresholds with `tap --100` or with coveralls :(

**Comment by alexindigo** [comment]
@mikeal you can totally integrate coverage between two (or runs). Just dump all the coverage files into the same folder (under different files names) and then let report tool to collect them all.

You can see it here, for example: https://github.com/alexindigo/deeply/blob/master/package.json#L10-L12

And travis runs it like this: https://github.com/alexindigo/deeply/blob/master/.travis.yml#L15-L18

**Comment by mikeal** [comment]
@alexindigo the problem is that most lines in the actual `test-browser.js` file don't show up as covered because they were run without coverage enabled :(

Also, I'm pretty sure the `--coverage` runner will clobber on each new run.

**Comment by alexindigo** [comment]
Not sure I'm following you completely, but if coverage is broken in the browser it's an issue.
But if you can split server-side and browser coverage into separate processes (as @bcoe suggested),
then you can have coverage files from both runs and run report for both of them.

Also, in general `tape` seems to be more browser friendly than `tap`, not sure if it's helpful at all or `tap` is the constant in this equation. :)

**Comment by mikeal** [comment]
@alexindigo here's the problem, the file for browser tests is executed by Node.js :) 

So, the file that manually implements coverage on the browser side can run fine (in Node.js and headless chrome) but breaks on the headless chrome side when I enable coverage on the Node.js side.

This means that the actual test file lines don't show up in the coverage report, only the lines in the library itself.

**Comment by alexindigo** [comment]
I see. Last time I checked (it was quite some time ago) – istanbul (and tap/nyc) would add custom js loader to node, to instrument loaded files. And it not the case with the browser. But things might change since then, so @bcoe or @isaacs would be better source of truth.

**Comment by bcoe** [comment]
@mikeal @alexindigo running `tap --coverage` is an alias for running `nyc tap foo.js`. Because tests are being run with `nyc`, the default behavior is that it will hook the `require` statement, and hook `child_process` such that any new processes spawned, or any new modules required will be transpiled using istanbul adding line counters that look something like `cov_vnbsudnht`.

The fact that you're getting a missing symbol for `cov_vnbsudnht` suggests to me that something in the process of bootstrapping puppeteer is clobbering these variables. puppeteer is probably being run in a Node subprocess, and keep in mind this tool would itself be potentially being instrumented for test coverage -- tldr I think this is the source of your woes.

One workaround I can think of would be to add an `exclude` rule to the `nyc` stanza of your `package.json` or creating a `.nycrc` that adds a rule something like this: `**/puppeteer/**`; what's weird, is anything in the `node_modules` folder should already be being ignored ... seems like something must be fiddling with `paths` as tests are run. Here's the docs on excluding files explicitly:

https://github.com/istanbuljs/nyc#excluding-files

**Comment by mikeal** [comment]
@bcoe I think I might know what it is. 

See these `evaluate` calls to puppeteer, https://github.com/mikeal/gza/blob/coverage/tests/test-browser.js#L166, they are some fancy magic that I'm pretty use end up doing a .toString() on the function and evaling it in the Chrome context.

When these get modified dynamically to call this function that is also showing up in the .toString(), but the function is actually missing from the browser context as it only exists in Node.js.

Update: this is probably the issue since `nyc --exclude=tests/test-browser.js tap tests/test-browser.js` works just fine.

**Comment by mikeal** [comment]
Update: can ensure 100% coverage and get everything to work now with a single command: `nyc --check-coverage --lines 100 --exclude=tests/test-browser.js tap tests/test-*.js`

**Comment by bcoe** [comment]
@mikeal awesome, if you're able to get instrumentation to skip on the puppeteer files (it's weird to me that it is running, as they're in the excluded `node_modules` folder) you might even be able to avoid having `nyc` in the mix.

**Comment by mikeal** [comment]
@bcoe instrumentation isn't running on the puppeteer files, it's just running on the test file. But the test file has code that gets toString()'d and evaluated inside headless chrome.

**Pull request merged**
