### PR TITLE
add instrumenter option parse

### PR DESCRIPTION
**Pull request by ouhouhsami**
Based on issue https://github.com/devongovett/browserify-istanbul/issues/7 I add the possibility to give a specific istanbul instrument for browserify-istanbul.

### CODE REVIEW

**Comment by bassettsj** [comment]
+1 here.

**Comment by devongovett** [comment]
Just merged #11 which allows passing an `instrumenterConfig` option to configure Istanbul. Does that work for you?

**Comment by lukescott** [comment]
This is also needed for isparta, which is similar but uses 6to5. The instrumenter needs to be replaced as it "sub-classes" istanbul to transform es6 code fix the line numbers.

The PR works, but has to be used like this:

```javascript
{transform: [istanbul({
	ignore: ["node_modules/**/*.js", "test/**/.js"],
	instrumenter: new (require("isparta")).Instrumenter()
}), "6to5ify"]}
```

I made a comment above, which should allow it to be this instead:

```javascript
{transform: [istanbul({
	ignore: ["node_modules/**/*.js", "test/**/.js"],
	instrumenter: require("isparta")
}), "6to5ify"]}
```

**Comment by simonzack** [comment]
:+1:, I'm also using isparta.

**Comment by devongovett** [comment]
Closing since #14 was merged.

**Pull request closed without merging**
